### ISSUE TITLE
Why is HasFocus persistable ?

### ISSUE THREAD

**Issue by NicolasBRUNAUD** [mwbouwkamp-mendix/treeGraphWidgets#1]
Hi Marco,

Thanks for these widgets, they look great and i want to use it !

I'm not sure to understand why the HasFocus attribute is persistable ?
What happens if 2 or more users navigate the same PERT at the same time ?
Do i miss something ?

**Comment by mwbouwkamp-mendix** [comment]
Hi Nicolas! 

Thank you for your positive feedback! With respect to your questions:
1. The reason the objects are persistable is for the creation of demo data. You can also work with non-persistable objects if you like.
2. Not sure what you mean here. The widget takes care of rendering the nodes on the screen. For the PERT, this is determined by its parent and child relationships and the designated column of the node. If two or more users navigate to the same PERT at the same time, they will just get their own view of the PERT diagram. In that respect it is the same as other data widgets in Mendix. For example, if two users are using a page with a datagrid, they can navigate, filter and sort the data independently from other users.

Hope this answers your questions!
Marco Bouwkamp
