### ISSUE TITLE
Slow scrolling when zoomed out in OrgChart

### ISSUE THREAD

**Issue by merijntiebie** [mwbouwkamp-mendix/treeGraphWidgets#15]
Thanks for the new release!

Another suggestion for the OrgChart:
- When the chart is zoomed out, the scrolling goes much slower compared to a regular zoom. For large hierarchies, it now takes quite long to go from one side of the chart to the other. It would be very convenient if you can zoom out and quickly scroll to the other side of the chart. Or include a scrollbar to facilate quick scrolling.
- Another nice improvment could be, that when you zoom in, that you zoom in to the point where you're mouse is at that moment. Now the screen zooms in to the element that has focus set to true.

**Comment by mwbouwkamp-mendix** [comment]
Version 1.2.0 has been released and should solve the scrolling issue
