### ISSUE TITLE
order of suppiler is not reflected in the pert chart

### ISSUE THREAD

**Issue by kyumyeoung** [mwbouwkamp-mendix/treeGraphWidgets#18]
MicroFlow does not execute
Supplier_SwapWithSuppliereOrderMinusOne

Even though the order value of the supplier has been changed (committed and refreshed in the client), the order is not reflected in the PERT chart as expected.
Is there any additional action that needs to be taken besides changing the supplier's order information to change the order of top and bottom in a PERT chart?
![image](https://github.com/mwbouwkamp-mendix/treeGraphWidgets/assets/164117745/ef6a768c-03cb-453a-a3de-a984268ecedf)

**Comment by mwbouwkamp-mendix** [comment]
It should not be necessary to do anything additional. Please follow/see if you can replicate the sample implementation. Hope that helps you moving forward.
