### ISSUE TITLE
z-index of buttons in pert (move up/down,...)

### ISSUE THREAD

**Issue by NicolasBRUNAUD** [mwbouwkamp-mendix/treeGraphWidgets#2]
in the sample, the buttons to move up/ down, edit, delete and add are not clickable.
Adding the following style to the parent container solves the issue.
z-index:1000;

**Comment by mwbouwkamp-mendix** [comment]
Hi Nicolas, Thank you for your feedback. Can you please investigate a little more to see what the issue could be? Do you have other (custom) css in your project that could cause this? If I go to the test project (either locally on my machine or in the sandbox), the buttons do work.

Sandbox: https://breakdownstructure-sandbox.mxapps.io/ (demo_administrator, XhbOCrXTnkl2)
