### ISSUE TITLE
Zooming out moves elements to bottom of panning area

### ISSUE THREAD

**Issue by merijntiebie** [mwbouwkamp-mendix/treeGraphWidgets#20]
I noticed that while zooming out in the org chart, the elements move to the bottom of the panning area. Afterwards I then drag the elements to the center of the screen again, to have the elements where I want them. However the elements shift to the bottom again after setting the focus. Ive attached a video to show the behavior:

https://github.com/mwbouwkamp-mendix/treeGraphWidgets/assets/62605685/1013fda6-4358-499c-af6b-166cbfb3e3e6

**Comment by mwbouwkamp-mendix** [comment]
Thanks for bringing this up. I have already fixed this and it will be part of the next release!

**Comment by merijntiebie** [comment]
Cool! Nice work!

**Comment by mwbouwkamp-mendix** [comment]
Version 1.2.0 has been released and should solve this issue
