### ISSUE TITLE
rendering problem?

### ISSUE THREAD

**Issue by rondv5** [mwbouwkamp-mendix/treeGraphWidgets#4]
Hi Marco,
I worked on duplicating your OrgChart example and put it against my own three-level deep entity structure.
I made an MF to take the data from the three levels and then create the nodes with the right parent and top-level organogram entity equivalents. I am seeing a rendering error where something that is on the third level that should belong to a separate 2nd level entity is being rendered in all 2nd level entities and not only in the one it belongs to according to the parent relationship.
I checked through the database content and can see all the right links made there, and I stepped the debugger through the data creation MF and saw correct behavior there as well.
Would you like to review and use my demo project to see if we have something here that needs resolution, or maybe I made such a brain fart that I was the culprit? (tried to do all the checks to exclude that before I wrote this, but one never knows)
If you want the demo project, how can I best get this to you? It has some proprietary content so I'd prefer to send it directly to you and not attach it to this Issue.

**Comment by mwbouwkamp-mendix** [comment]
Hi @rondv5,

Thank you for reaching out. Could you (for now) please provide me with a description of the data (including parent-child relationships) and a screenshot of the result you are getting?

Regards,
Marco

**Comment by rondv5** [comment]
@mwbouwkamp-mendix .
Can you reach out to me on ron@bizkase.com? I'd like to send the things you asked for there so I don't need to rebuild the project to anonimize it.

**Comment by mwbouwkamp-mendix** [comment]
Hello @rondv5

Thank you for sharing your project with me. I have found the issue, but it is not in the widget, but in your implementation. You need to use a unique id as a `descriptor` and as the attribute for the `parent association`. You were using `SourceType` instead and `SourceType` in your implementation is not unique. 

Regards,
Marco
