### ISSUE TITLE
Arrows disappeared in parts of the Pert chart widget.

### ISSUE THREAD

**Issue by carolinaneiva** [mwbouwkamp-mendix/treeGraphWidgets#7]
When using a larger amount of data than the examples, the arrow disappears.
![image](https://github.com/mwbouwkamp-mendix/treeGraphWidgets/assets/69816656/8bfa732d-ee36-4e02-8845-d2b41ceaab9b)

**Comment by mwbouwkamp-mendix** [comment]
@carolinaneiva: Did you freshly download the module? I have published a new version on Friday. This should have been fixed in this version.
