### ISSUE TITLE
Suggestions for OrgChart

### ISSUE THREAD

**Issue by merijntiebie** [mwbouwkamp-mendix/treeGraphWidgets#8]
I really like this widget. Great work and very cool that much of the configuration & styling can be done in Mendix itself.

A couple of suggestions for improvements:
- In the OrgChart, some elements seem to bounce from the screen for a sec, when clicking the 'showChildrens' arrow. When for example in the demo project of the OrgChart I click on the arrow to show the children of the CEO, it seems this card dissapears from the screen for a short moment. Similar, when I click on the arrow to show the children of the CTO, the CEO seems to dissapear for a short sec, after which it renders at the same spot as before. Is it possible to have this element steady on the screen instead?
- In the orgChart, the zoom percentage gets lost when I perform an action that requires a reload of the chart. It would be nice if the zoom % is persistent. Or to make it configurable to persist the zoom %or not.

**Comment by mwbouwkamp-mendix** [comment]
Thank you @merijntiebie for your input!

**Comment by mwbouwkamp-mendix** [comment]
@merijntiebie, thank you for your suggestions. Both issues have been fixed and will be available in the next release.
